# Generated by Django 4.2.4 on 2023-10-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_zapatos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
