# Generated by Django 4.2.4 on 2023-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_avatar_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
