# Generated by Django 4.2.4 on 2023-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_avatar_predeterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatos',
            name='imagen',
            field=models.ImageField(upload_to='media/zapatos/'),
        ),
    ]
